Added basic checks to ensure the correct version of Docker Compose is installed.
DataDog/KubeHound pull request #155
Opened 2023-12-21 14:20 UTC by felix-caboff

Safety check to ensure the correct version of docker compose is installed.  Used the existing docker detection logic to ensure that the correct version is found.

2023-12-26 09:20 UTC, edznux-dd commented
Hey thanks for the PR.
I'm not sure the string matching is correct?
I have `Docker Compose version v2.21.0` on my machine, so it doesn't match `grep '^Docker Compose version 2'` what do you have on yours?

2023-12-26 09:21 UTC, edznux-dd requested changes

2023-12-26 09:21 UTC, edznux-dd commented on scripts/kubehound.sh
> +    if ! [ "$(docker compose version | grep '^Docker Compose version 2')" ]; then
```suggestion
    if ! [ "$(docker compose version | grep '^Docker Compose version v2')" ]; then
```
I think?

2024-02-21 09:34 UTC, d0g0x01 commented on scripts/kubehound.sh
> +    if ! [ "$(docker compose version | grep '^Docker Compose version v2')" ]; then
what about when v3 is released?

2024-06-13 10:09 UTC, edznux-dd commented
Hey, we have reworked a bit the Makefile to be *way* more user friendly as part of #200!

It is available as part of the pre-release already but we will also ship a "real version" soon.

Closing that PR, thanks for the work though!
And sorry for the delay here.

2024-06-13 10:09 UTC, closed without merging