graphdb batch writer resiliency
DataDog/KubeHound pull request #295
Opened 2024-11-28 14:14 UTC by Zenithar

# Context

The graphdb entity writers can be subject to unexpected behaviours from the JanusGraph backend (eg. backend not responding due to runtine errors).
The writers have been modified to add resilience to unexpected situation:
* Writers are bound in time (default: 60s) 
* A retry pattern allows a batch to be retried with an upper limit (default: 3)
* Each batch size is divided by 2 to reduce the size of each attempts

2024-11-28 15:12 UTC, jt-dd requested changes
Currently not working as the async synchro is not properly done. Also maybe adding a dedicated function to add element into the queue.

2024-11-28 15:12 UTC, jt-dd commented on pkg/kubehound/storage/graphdb/janusgraph_vertex_writer.go
> +								jgv.consumerChan <- batchItem{
Same as previously:

```suggestion
								jgv.writingInFlight.Add(1)
								_ = statsd.Incr(ctx, metric.QueueSize, jgv.tags, 1)
								jgv.consumerChan <- batchItem{
```

2024-11-28 15:12 UTC, jt-dd commented on pkg/kubehound/storage/graphdb/janusgraph_vertex_writer.go
> +								jgv.consumerChan <- batchItem{
Same as previously:

```suggestion
								jgv.writingInFlight.Add(1)
								_ = statsd.Incr(ctx, metric.QueueSize, jgv.tags, 1)
								jgv.consumerChan <- batchItem{
```

2024-11-29 09:23 UTC, Zenithar commented on pkg/kubehound/storage/graphdb/janusgraph_vertex_writer.go
> +								jgv.consumerChan <- batchItem{
Not applicable anymore.

2024-11-29 09:23 UTC, Zenithar commented on pkg/kubehound/storage/graphdb/janusgraph_vertex_writer.go
> +								jgv.consumerChan <- batchItem{
Not applicable anymore.

2024-11-29 09:24 UTC, Zenithar commented on pkg/kubehound/storage/graphdb/janusgraph_edge_writer.go
> +								jgv.consumerChan <- batchItem{
Not applicable anymore.

2024-11-29 09:24 UTC, Zenithar commented on pkg/kubehound/storage/graphdb/janusgraph_edge_writer.go
> +								jgv.consumerChan <- batchItem{
Not applicable anymore.

2024-11-29 09:25 UTC, Zenithar commented on pkg/kubehound/storage/graphdb/provider.go
> +func WithWriterTimeout(timeout time.Duration) WriterOption {
No, it should be wired to the configuration state.

2024-11-29 09:25 UTC, Zenithar commented on pkg/kubehound/storage/graphdb/provider.go
> +func WithWriterMaxRetry(maxRetry int) WriterOption {
No, it should be wired to the configuration state.

2024-11-29 10:10 UTC, Zenithar commented on pkg/kubehound/storage/graphdb/provider.go
> +func WithWriterTimeout(timeout time.Duration) WriterOption {
Done.

2024-12-02 19:17 UTC, merged